name: Zap Scan

on:
  push:
    branches: [ build, prod, test ]
  pull_request:
    branches: [ build, prod, test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.3.0
      with:
        target: 'https://sbrendan.github.io/EcoTree/index.html'
      